name: CI

on:
  push:
    branches:
      - main
      - gh-actions
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Package add-on
        working-directory: src/omnidict
        run: zip -r ../../OmniDict.ankiaddon *
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: OmniDict.ankiaddon
          path: OmniDict.ankiaddon
          archive: false

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Run tests
        run: uv run pytest --junit-xml=pytest-junit.xml
      - name: Upload test report
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: pytest-junit.xml
