name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Copy LICENSE file to add-on directory
        run: cp LICENSE src/omnidict/
      - name: Package add-on
        working-directory: src/omnidict
        run: zip -r ../../OmniDict.ankiaddon *
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: src/omnidict
          output-file: ./sbom.spdx.json
      - name: Generate artifact attestation
        uses: actions/attest@v4
        if: github.ref_type == 'tag'  # Only generate attestation for tagged commits (releases)
        with:
          subject-path: ./OmniDict.ankiaddon
          sbom-path: ./sbom.spdx.json
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: OmniDict.ankiaddon
          path: OmniDict.ankiaddon
          archive: false

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Run tests
        run: uv run pytest --junit-xml=pytest-junit.xml
      - name: Upload test report
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: pytest-junit.xml

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Run linter
        run: uv run ruff check --output-format=github
      - name: Run formatter
        run: uv run ruff format --check --preview --output-format=github
      - name: Run type checker
        run: uv run ty check --output-format=github

  release:
    runs-on: ubuntu-latest
    needs: [ package, test, lint ]
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: OmniDict.ankiaddon
          skip-decompress: true
      - name: Generate release name
        id: release-name
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: echo "release-name=${TAG_NAME#v}" >> "$GITHUB_OUTPUT"
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ steps.release-name.outputs.release-name }}
          files: OmniDict.ankiaddon
          generate_release_notes: true
      - name: Upload add-on to AnkiWeb
        uses: danny900714/upload-anki-addon@v1
        with:
          username: ${{ secrets.ANKIWEB_USERNAME }}
          password: ${{ secrets.ANKIWEB_PASSWORD }}
          addon-id: ${{ vars.ANKIWEB_ADDON_ID }}
          title: OmniDict - All Dictionaries in one add-on
          tags: dictionary AnkiDroid AnkiMobile Chinese Cambridge
          support-page: ${{ format('{0}/{1}', github.server_url, github.repository) }}
          description-file: DESCRIPTION.md
          branches: 25.07-26.05+
          addon-files: OmniDict.ankiaddon
