name: Test Report

on:
  workflow_run:
    workflows:
      - CI/CD
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Create test report
        uses: dorny/test-reporter@v3
        with:
          artifact: test-results
          name: pytest tests
          path: pytest-junit.xml
          reporter: python-xunit
